include:
 - '/.gitlab-ci.yml'


build_samba:
  stage: build
  tags:
    - docker
    - private
  script:
    # this one takes about 4 hours to finish
    - python script/autobuild.py samba            --verbose --tail --testbase /tmp/samba-testbase

build_samba_nt4:
  stage: build
  tags:
    - docker
    - private
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-nt4        --verbose --tail --testbase /tmp/samba-testbase

build_samba_fileserver:
  stage: build
  tags:
    - docker
    - private
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-fileserver --verbose --tail --testbase /tmp/samba-testbase

build_samba_ad_dc:
  stage: build
  tags:
    - docker
    - private
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-ad-dc     --verbose --tail --testbase /tmp/samba-testbase

build_samba_ad_dc_2:
  stage: build
  tags:
    - docker
    - private
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-ad-dc-2     --verbose --tail --testbase /tmp/samba-testbase
