include:
 - '/.gitlab-ci.yml'


.private_template:
  extends: .shared_template
  tags:
    - docker
    - private
  before_script:
    - uname -a
    - lsb_release -a
    - mount
    - df -h
    - free -h

samba:
  extends: .private_template
  # this one takes about 4 hours to finish

samba-fileserver:
  extends: .private_template
  # this one takes about 1 hours to finish

samba-ad-dc:
  extends: .private_template
  # this one takes about 1 hours to finish

samba-nt4:
  extends: .private_template
