# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


variables:
  SAMBA_BUILD_GITLAB_CI_REGISTRY: registry.gitlab.com
  SAMBA_BUILD_IMAGES_PROJECT: samba-team/samba
  SAMBA_BUILD: latest
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

.shared_template:
  image: $SAMBA_BUILD_GITLAB_CI_REGISTRY/$SAMBA_BUILD_IMAGES_PROJECT:$SAMBA_BUILD
  stage: build
  tags:
    - docker
    - shared
  before_script:
    - uname -a
    - lsb_release -a
    - echo "Build starting (preparing swap)..."
    - if [ $(df -m / --output=avail | tail -n1) -gt 10240 ]; then
        sudo dd if=/dev/zero of=/samba-swap bs=1M count=6144;
        sudo mkswap /samba-swap;
        sudo swapon /samba-swap;
      fi
    - mount
    - df -h
    - free -h
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - "*.stdout"
      - "*.stderr"
      - system-info.txt
      - /tmp/samba-testbase/*/*/bin/config.log
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - script/autobuild.py $CI_JOB_NAME    --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

others:
  extends: .shared_template
  script:
    - script/autobuild.py ldb              --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py pidl             --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py replace          --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py talloc           --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py tdb              --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py tevent           --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

samba-none-env:
  extends: .shared_template
  # this one takes about 1 hours to finish

samba-none-env-py2:
  extends: .shared_template
  # this one takes about 1 hours to finish

samba-nopython:
  extends: .shared_template

samba-systemkrb5:
  extends: .shared_template

samba-xc:
  extends: .shared_template

samba-o3:
  extends: .shared_template

samba-ad-dc-2:
  extends: .shared_template
  # this one takes about 1 hours to finish

samba-ad-dc-backup:
  extends: .shared_template

samba-ad-dc-2-py2:
  extends: .shared_template
  # this one takes about 1 hours to finish

samba-libs:
  extends: .shared_template

samba-libs-py2:
  extends: .shared_template

samba-static:
  extends: .shared_template

ctdb:
  extends: .shared_template

samba-ctdb:
  extends: .shared_template

samba-buildpy2-only:
  extends: .shared_template

samba-ad-dc-ntvfs:
  extends: .shared_template
  # this one takes about 100 mins to finish

samba-ad-dc-ntvfs-py2:
  extends: .shared_template
