# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


variables:
  SAMBA_BUILD_IMAGES_PROJECT: samba-team/samba
  SAMBA_BUILD: latest
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

.shared_template: &shared_template
  image: $CI_REGISTRY/$SAMBA_BUILD_IMAGES_PROJECT:$SAMBA_BUILD
  stage: build
  tags:
    - docker
    - shared
  before_script:
    - echo "Build starting (preparing swap)..."
    - if [ $(df -m / --output=avail | tail -n1) -gt 10240 ]; then
        sudo dd if=/dev/zero of=/samba-swap bs=1M count=6144;
        sudo mkswap /samba-swap;
        sudo swapon /samba-swap;
      fi
  after_script:
    - tar -xf logs.tar.gz system-info.txt -O

build_samba_none_env:
  <<: *shared_template
  script:
    # this one takes about 1 hours to finish
    - script/autobuild.py samba-none-env    --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_none_env_py2:
  <<: *shared_template
  script:
    # this one takes about 1 hours to finish
    - script/autobuild.py samba-none-env-py2    --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_nopython:
  <<: *shared_template
  script:
    - script/autobuild.py samba-nopython   --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_systemkrb5:
  <<: *shared_template
  script:
    - script/autobuild.py samba-systemkrb5 --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_xc:
  <<: *shared_template
  script:
    - script/autobuild.py samba-xc         --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_o3:
  <<: *shared_template
  script:
    - script/autobuild.py samba-o3         --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_ad_dc_2:
  <<: *shared_template
  script:
    # this one takes about 1 hours to finish
    - script/autobuild.py samba-ad-dc-2     --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_ad_dc_2_py2:
  <<: *shared_template
  script:
    # this one takes about 1 hours to finish
    - script/autobuild.py samba-ad-dc-2-py2     --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_libs:
  <<: *shared_template
  script:
    - script/autobuild.py samba-libs       --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_libs_py2:
  <<: *shared_template
  script:
    - script/autobuild.py samba-libs-py2       --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_static:
  <<: *shared_template
  script:
    - script/autobuild.py samba-static     --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_ctdb:
  <<: *shared_template
  script:
    - script/autobuild.py ctdb       --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_ctdb:
  <<: *shared_template
  script:
    - script/autobuild.py samba-ctdb             --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_others:
  <<: *shared_template
  script:
    - script/autobuild.py ldb              --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py pidl             --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py replace          --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py talloc           --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py tdb              --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase
    - script/autobuild.py tevent           --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_buildpy2_only:
  <<: *shared_template
  script:
    - python script/autobuild.py samba-buildpy2-only             --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

